const fs = require('fs');
const path = require('path');
const { BOT_CONFIG } = require('../config');

const storePath = path.join(BOT_CONFIG.dataDir, 'format.json');

const DEFAULTS = {
  language: 'pt',      // 'pt' | 'en'
  legend: true,        // show emoji legend at bottom
  header: true,        // show "Gerado automaticamente..." quote
  titlePrefix: 'Stand-up', // page title prefix
};

const LABELS = {
  pt: {
    yesterday: 'Ontem eu fiz:',
    today: 'Hoje vou focar em:',
    blockers: 'Bloqueios:',
    none: 'Nenhum.',
    autoHeader: 'Gerado automaticamente pelo bot de stand-up.',
    legend: '[✅=Feito][🟨=Fazendo][🟫=Não trabalhado]',
  },
  en: {
    yesterday: 'Yesterday I worked on:',
    today: "Today I'll focus on:",
    blockers: 'Blockers:',
    none: 'None.',
    autoHeader: 'Auto-generated by the stand-up bot.',
    legend: '[✅=Done][🟨=Doing][🟫=Not worked]',
  },
};

let store = null;

function load() {
  try {
    store = { ...DEFAULTS, ...JSON.parse(fs.readFileSync(storePath, 'utf8')) };
  } catch {
    store = { ...DEFAULTS };
  }
  return store;
}

function save() {
  fs.writeFileSync(storePath, JSON.stringify(store, null, 2));
}

function get() {
  if (!store) load();
  return { ...store };
}

function set(updates) {
  if (!store) load();
  Object.assign(store, updates);
  save();
}

function getLabels() {
  if (!store) load();
  return LABELS[store.language] ?? LABELS.pt;
}

module.exports = { load, get, set, getLabels, LABELS };
